import React,{useEffect,useState} from 'react';import CodeMirror from '@uiw/react-codemirror';import{sql}from '@codemirror/lang-sql';import initSqlJs from 'sql.js';import wasmUrl from 'sql.js/dist/sql-wasm.wasm?url';import chapter from '../content/chapter-01.json';
type Mission={id:string;title:string;description?:string;task?:string;prompt?:string;starterSql?:string;solutionSql?:string;referenceSql?:string;hints?:string[];orderMatters?:boolean;validation?:{referenceSql?:string;type?:string}};
type Output={columns:string[];values:unknown[][]};
const missions=((chapter as any).missions??(chapter as any).exercises??(chapter as any).lessons??[]) as Mission[];
function normalize(o:Output){return JSON.stringify(o.values.map(v=>JSON.stringify(v)).sort())}
export default function App(){
 const [db,setDb]=useState<any>(null),[error,setError]=useState(''),[index,setIndex]=useState(0),[query,setQuery]=useState(''),[result,setResult]=useState<Output|null>(null),[message,setMessage]=useState(''),[hint,setHint]=useState(0);
 const [done,setDone]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('titanic-done')||'[]')}catch{return[]}});
 const mission=missions[index];const starter=(m?:Mission)=>m?.starterSql??'SELECT * FROM passengers LIMIT 5;';
 useEffect(()=>{setQuery(localStorage.getItem('titanic-query-'+(mission?.id??index))??starter(mission));setMessage('');setResult(null);setHint(0)},[index]);
 useEffect(()=>{if(mission)localStorage.setItem('titanic-query-'+mission.id,query)},[query,mission?.id]);
 useEffect(()=>{let active=true;async function load(){try{const SQL=await initSqlJs({locateFile:f=>wasmUrl});const response=await fetch(import.meta.env.BASE_URL+'data/titanic-ch01.sqlite');if(!response.ok)throw Error('Database could not load');const bytes=new Uint8Array(await response.arrayBuffer());if(active)setDb(new SQL.Database(bytes))}catch(e){if(active)setError(String(e))}}load();return()=>{active=false}},[]);
 function run(q=query):Output{if(!db)throw Error('Database is loading');if(!/^\s*(SELECT|WITH|PRAGMA)\b/i.test(q))throw Error('Only read-only SQL queries are allowed in this chapter');const res=db.exec(q);return res.length?{columns:res[0].columns,values:res[0].values}:{columns:[],values:[]}}
 function execute(){try{setResult(run());setError('');setMessage('Query executed. Check answer when ready.')}catch(e){setError(String(e));setMessage('')}}
 function check(){try{const actual=run();setResult(actual);const reference=mission?.validation?.referenceSql??mission?.referenceSql??mission?.solutionSql;if(!reference){setMessage('Query executed. This exercise has no automatic reference answer yet.');return}const expected=run(reference);const ok=JSON.stringify(actual.columns)===JSON.stringify(expected.columns)&&(mission?.orderMatters?JSON.stringify(actual.values)===JSON.stringify(expected.values):normalize(actual)===normalize(expected));setMessage(ok?'Excellent! Your query produces the expected results.':'Not quite. Check the requested columns and rows, then try again.');setError('');if(ok&&mission&&!done.includes(mission.id)){const next=[...done,mission.id];setDone(next);localStorage.setItem('titanic-done',JSON.stringify(next))}}catch(e){setError(String(e))}}
 return <main><header><div className="brand">⚓ TITANIC DATA ACADEMY</div><span>SQL & Data Fundamentals · Chapter 1</span></header><section className="hero"><p className="eyebrow">THE HISTORICAL ARCHIVE · 1912</p><h1>The Passenger Manifest</h1><p>Learn real SQL while exploring the records of an extraordinary voyage. Chapter 1 uses fictional training passengers for safe practice.</p><div className="progress"><div style={{width:(missions.length?100*done.length/missions.length:0)+'%'}}/></div><small>{done.length} of {missions.length} missions completed</small></section><div className="layout"><aside><h2>Your missions</h2>{missions.map((m,i)=><button key={m.id??i} className={'mission '+(i===index?'active':'')} onClick={()=>setIndex(i)}>{done.includes(m.id)?'✓ ':'○ '}{m.title??'Mission '+(i+1)}</button>)}<p className="note">All work is saved in this browser. No account required.</p></aside><section className="workspace"><div className="panel"><p className="eyebrow">ASSIGNMENT {index+1}</p><h2>{mission?.title??'Explore the passenger manifest'}</h2><p>{mission?.task??mission?.description??mission?.prompt??'Explore the passengers table using SQL.'}</p><div className="schema"><b>DATABASE EXPLORER</b><p>▦ passengers</p><small>Use <code>SELECT * FROM passengers LIMIT 5;</code> to inspect its columns.</small></div></div><div className="panel"><div className="between"><h3>SQL Workspace</h3><small>SQLite · Read only</small></div><CodeMirror value={query} height="210px" extensions={[sql()]} onChange={setQuery} theme="dark"/><div className="actions"><button onClick={execute} disabled={!db}>▶ Run query</button><button className="primary" onClick={check} disabled={!db}>✓ Check answer</button><button onClick={()=>{setQuery(starter(mission));setResult(null);setMessage('')}}>Reset</button></div>{error&&<p className="error">{error}</p>}{message&&<p className="feedback">{message}</p>}{(mission?.hints?.length??0)>0&&<><button className="text-button" onClick={()=>setHint(Math.min(hint+1,mission.hints!.length))}>Need a hint?</button>{hint>0&&<p className="hint">{mission.hints[hint-1]}</p>}</>}</div><div className="panel"><div className="between"><h3>Query results</h3><small>{result?result.values.length+' rows':'Run a query to see results'}</small></div>{result?<div className="scroll"><table><thead><tr>{result.columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{result.values.slice(0,100).map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v===null?'NULL':String(v)}</td>)}</tr>)}</tbody></table></div>:<p className="empty">Your query results will appear here.</p>}</div></section></div><footer>Inspired by the history of RMS Titanic · Not affiliated with any film production</footer></main>
}